### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by motatoes**

### CODE REVIEW

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
digger plan

**Comment by dggrmike** [comment]
<details><summary>Digger run report at 2023-07-27 14:13:04 (UTC)</summary>
  <details><summary>Locking successful</summary>
  Project diggerhq/drift-detection-demo#dev has been locked by PR #1
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by dggrmike** [comment]
<details><summary>Digger run report at 2023-07-27 14:16:33 (UTC)</summary>
    <details><summary>Plan for <b>diggerhq/drift-detection-demo#dev</b></summary>
  
```terraform
Terraform will perform the following actions:

  # aws_security_group.allow_tls will be created
  + resource "aws_security_group" "allow_tls" {
      + arn                    = (known after apply)
      + description            = "Allow TLS inbound traffic"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "172.30.0.0/16",
                ]
              + description      = "TLS from VPC"
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
        ]
      + name                   = "allow_tls"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "allow_tls"
        }
      + tags_all               = {
          + "Name" = "allow_tls"
        }
      + vpc_id                 = "vpc-089be2add61f9704f"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (dev)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
digger apply

**Comment by dggrmike** [comment]
<details><summary>Digger run report at 2023-07-27 14:22:37 (UTC)</summary>
  <details><summary>Apply for <b>diggerhq/drift-detection-demo#dev</b></summary>
  
```terraform
Terraform will perform the following actions:

  # aws_security_group.allow_tls will be created
  + resource "aws_security_group" "allow_tls" {
      + arn                    = (known after apply)
      + description            = "Allow TLS inbound traffic"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "172.30.0.0/16",
                ]
              + description      = "TLS from VPC"
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
        ]
      + name                   = "allow_tls"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "allow_tls"
        }
      + tags_all               = {
          + "Name" = "allow_tls"
        }
      + vpc_id                 = "vpc-089be2add61f9704f"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
aws_security_group.allow_tls: Creating...
aws_security_group.allow_tls: Creation complete after 2s [id=sg-022fdc6cfd57c756a]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Pull request closed without merging**
